// eslint-disable-next-line camelcase
import { Inter, Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer/Footer";
import Navbar from "@/components/shared/Navbar/Navbar";
import React from "react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["400", "700"],
});

const notoSansThai = Noto_Sans_Thai({
  subsets: ["thai"],
  variable: "--font-noto-sans-thai",
  display: "swap",
  weight: ["400", "700"],
});

export const metadata = {
  title: "P.P Freshpork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <head>
        <link rel="icon" href="/ppfreshpork-logo.ico" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body
        className={`container ${inter.variable} ${notoSansThai.variable} flex h-full min-h-screen flex-col gap-8 overflow-scroll font-sans antialiased lg:gap-16`}
      >
        <Navbar />
        <main className="grow rounded-lg bg-white">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
